ingestion:
  rest-ingestion:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "500m"
      hosts:
        - host: ingestion.127.0.0.1.nip.io
        - host: host.docker.internal
delivery:
  blueprint-web:
    ingress:
      enabled: true
      hosts:
        - host: puresight.127.0.0.1.nip.io
          paths:
            - servicePort: 80
  blueprint-search:
    ingress:
      enabled: true
      hosts:
        - host: puresight.127.0.0.1.nip.io
          paths:
            - path: /search

